version = 0.1

[default]
[default.global.parameters]
stack_name = "cloudfront-hosting-sample"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
region = "ap-northeast-1"
image_repositories = []
parameter_overrides = [
  "OriginBucket=<bucket>"
]
